export const ROLES = {
  DISTRICT_AUTHORITY: 'DISTRICT_AUTHORITY',
  IMPLEMENTING_AGENCY: 'IMPLEMENTING_AGENCY',
  VENDOR: 'VENDOR',
  STATE_NODAL_AUTHORITY: 'STATE_NODAL_AUTHORITY',
  CENTRAL_NODAL_AGENCY: 'CENTRAL_NODAL_AGENCY',
  MP: 'MP',
  INVESTIGATOR: 'INVESTIGATOR',
};

export const AGENCY_TYPES = [
  'PWD (Public Works Department)',
  'Rural Development Department',
  'Municipal Corporation',
  'Zila Panchayat',
  'Public Health Engineering Department (PHED)',
  'Education Infrastructure Cell',
];

export const DEFAULT_PROFILES = {
  [ROLES.DISTRICT_AUTHORITY]: {
    role: ROLES.DISTRICT_AUTHORITY,
    roleTitle: 'DISTRICT AUTHORITY',
    subTitle: 'Bhopal, Madhya Pradesh',
    organizationName: 'District Collectorate & Nodal Office',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    userId: 'DA-BPL-001',
    userName: 'R. Venkatraman, IAS',
    designation: 'District Collector & Nodal Officer',
    landingRoute: '/district-dashboard',
  },
  [ROLES.IMPLEMENTING_AGENCY]: {
    role: ROLES.IMPLEMENTING_AGENCY,
    roleTitle: 'IMPLEMENTING AGENCY',
    agencyType: 'PWD (Public Works Department)',
    subTitle: 'PWD • Bhopal, Madhya Pradesh',
    organizationName: 'Public Works Department (Central Zone)',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    userId: 'PWD-BPL-IA-001',
    userName: 'Er. S. K. Sharma',
    designation: 'Executive Engineer (Division-II)',
    landingRoute: '/dashboard',
  },
  [ROLES.VENDOR]: {
    role: ROLES.VENDOR,
    roleTitle: 'VENDOR / CONTRACTOR',
    subTitle: 'Eastern Structural • VND-007',
    organizationName: 'Eastern Structural & Engineering Co.',
    vendorId: 'VND-007',
    state: 'West Bengal',
    district: 'Nadia',
    userId: 'VND-007-USER',
    userName: 'P. K. Banerjee',
    designation: 'Authorized Signatory',
    landingRoute: '/vendor-dashboard',
  },
  [ROLES.STATE_NODAL_AUTHORITY]: {
    role: ROLES.STATE_NODAL_AUTHORITY,
    roleTitle: 'STATE NODAL AUTHORITY',
    subTitle: 'Planning Dept • Madhya Pradesh',
    organizationName: 'State Planning & Nodal Directorate',
    state: 'Madhya Pradesh',
    district: 'Statewide',
    userId: 'SNA-MP-001',
    userName: 'Anita Deshmukh, IAS',
    designation: 'Principal Secretary (Planning)',
    landingRoute: '/state-dashboard',
  },
  [ROLES.CENTRAL_NODAL_AGENCY]: {
    role: ROLES.CENTRAL_NODAL_AGENCY,
    roleTitle: 'CENTRAL NODAL AGENCY',
    subTitle: 'MoSPI • New Delhi',
    organizationName: 'Ministry of Statistics & Programme Implementation',
    state: 'National',
    district: 'All States & UTs',
    userId: 'CNA-MOSPI-001',
    userName: 'Dr. Alok Verma',
    designation: 'Joint Secretary (MPLADS Division)',
    landingRoute: '/national-dashboard',
  },
  [ROLES.MP]: {
    role: ROLES.MP,
    roleTitle: 'MEMBER OF PARLIAMENT',
    subTitle: 'Bhopal Constituency (MP-Lok Sabha)',
    organizationName: 'Parliamentary Constituency Office',
    state: 'Madhya Pradesh',
    constituency: 'Bhopal (PC-19)',
    userId: 'MP-LS-BPL-19',
    userName: 'Shri R. K. Singh, MP',
    designation: 'Member of Parliament (Lok Sabha)',
    landingRoute: '/mp-dashboard',
  },
  [ROLES.INVESTIGATOR]: {
    role: ROLES.INVESTIGATOR,
    roleTitle: 'INSPECTOR / INVESTIGATOR',
    subTitle: 'Special Vigilance Cell • Central Zone',
    organizationName: 'SAKSHAM Statutory Vigilance Cell',
    state: 'Multi-State',
    district: 'Central Zone',
    userId: 'VIG-INSP-042',
    userName: 'Vikramaditya Roy',
    designation: 'Senior Vigilance & Risk Auditor',
    landingRoute: '/investigations',
  },
};
