/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#e5eeff",
        "status-success-text": "#047857",
        "primary-fixed": "#dce1ff",
        "primary": "#0043c4",
        "on-surface": "#0b1c30",
        "error-container": "#ffdad6",
        "surface-container-low": "#eff4ff",
        "status-success-dot": "#10B981",
        "border-strong": "#CBD5E1",
        "surface-bright": "#f8f9ff",
        "surface": "#f8f9ff",
        "error": "#ba1a1a",
        "status-warning-dot": "#F59E0B",
        "primary-fixed-dim": "#b6c4ff",
        "secondary-fixed-dim": "#afc6ff",
        "border-subtle": "#E2E8F0",
        "status-info-bg": "#EFF6FF",
        "on-tertiary-fixed-variant": "#28418f",
        "tertiary-container": "#4c64b3",
        "on-secondary-container": "#fefcff",
        "background": "#f8f9ff",
        "outline": "#737687",
        "status-success-bg": "#ECFDF5",
        "on-tertiary-fixed": "#00164f",
        "text-primary": "#0F172A",
        "on-secondary-fixed": "#001944",
        "secondary-container": "#216fea",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary": "#ffffff",
        "surface-base": "#F8FAFC",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#004299",
        "on-error": "#ffffff",
        "primary-container": "#1a5af0",
        "on-primary-container": "#e3e7ff",
        "status-danger-dot": "#EF4444",
        "inverse-primary": "#b6c4ff",
        "surface-subtle": "#EDF2F9",
        "status-danger-text": "#B91C1C",
        "text-muted": "#94A3B8",
        "on-primary-fixed-variant": "#003baf",
        "text-secondary": "#475569",
        "on-primary-fixed": "#00164e",
        "status-info-text": "#1D4ED8",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed": "#d9e2ff",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#e4e7ff",
        "status-info-dot": "#3B82F6",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#b6c4ff",
        "inverse-surface": "#213145",
        "status-warning-text": "#B45309",
        "surface-tint": "#004fe4",
        "outline-variant": "#c3c5d8",
        "on-surface-variant": "#434655",
        "tertiary-fixed": "#dce1ff",
        "status-warning-bg": "#FFFBEB",
        "on-error-container": "#93000a",
        "surface-dim": "#cbdbf5",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "status-danger-bg": "#FEF2F2",
        "secondary": "#0056c3",
        "tertiary": "#334b99",
        "surface-card": "#FFFFFF",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "1rem",
        "space-md": "1rem",
        "space-2xl": "3rem",
        "space-xs": "0.25rem",
        "gutter": "1.25rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "0.75rem",
        "margin": "2rem",
      },
      fontFamily: {
        sans: ["Geist", "system-ui", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        "display-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.015em", fontWeight: "500" }],
        "metric-val": ["30px", { lineHeight: "36px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-xs": ["11px", { lineHeight: "14px", letterSpacing: "0.025em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
