export const PROJECT_STATUS = {
  RECOMMENDED: 'RECOMMENDED',
  APPROVED: 'APPROVED',
  SANCTIONED: 'SANCTIONED',
  UNDER_IMPLEMENTATION: 'UNDER_IMPLEMENTATION',
  INSPECTION_REQUIRED: 'INSPECTION_REQUIRED',
  ON_HOLD: 'ON_HOLD',
  VERIFIED: 'VERIFIED',
  COMPLETED: 'COMPLETED',
  FINANCIALLY_CLOSED: 'FINANCIALLY_CLOSED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

const ALLOWED_TRANSITIONS = {
  [PROJECT_STATUS.RECOMMENDED]: [PROJECT_STATUS.APPROVED, PROJECT_STATUS.REJECTED],
  [PROJECT_STATUS.APPROVED]: [PROJECT_STATUS.SANCTIONED, PROJECT_STATUS.REJECTED],
  [PROJECT_STATUS.SANCTIONED]: [PROJECT_STATUS.UNDER_IMPLEMENTATION, PROJECT_STATUS.ON_HOLD, PROJECT_STATUS.CANCELLED],
  [PROJECT_STATUS.UNDER_IMPLEMENTATION]: [PROJECT_STATUS.INSPECTION_REQUIRED, PROJECT_STATUS.ON_HOLD, PROJECT_STATUS.VERIFIED],
  [PROJECT_STATUS.INSPECTION_REQUIRED]: [PROJECT_STATUS.VERIFIED, PROJECT_STATUS.ON_HOLD, PROJECT_STATUS.UNDER_IMPLEMENTATION],
  [PROJECT_STATUS.ON_HOLD]: [PROJECT_STATUS.UNDER_IMPLEMENTATION, PROJECT_STATUS.INSPECTION_REQUIRED, PROJECT_STATUS.VERIFIED, PROJECT_STATUS.CANCELLED],
  [PROJECT_STATUS.VERIFIED]: [PROJECT_STATUS.COMPLETED, PROJECT_STATUS.ON_HOLD],
  [PROJECT_STATUS.COMPLETED]: [PROJECT_STATUS.FINANCIALLY_CLOSED, PROJECT_STATUS.ON_HOLD],
  [PROJECT_STATUS.FINANCIALLY_CLOSED]: [],
  [PROJECT_STATUS.REJECTED]: [],
  [PROJECT_STATUS.CANCELLED]: [],
};

export function isValidTransition(currentStatus, targetStatus) {
  if (!currentStatus || !targetStatus) return false;
  if (currentStatus === targetStatus) return true;
  const allowed = ALLOWED_TRANSITIONS[currentStatus];
  return allowed ? allowed.includes(targetStatus) : false;
}
